/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceIdSlotsRouteImport } from './routes/services.$serviceId.slots'
import { Route as ServicesServiceIdDateRouteImport } from './routes/services.$serviceId.date'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesServiceIdSlotsRoute = ServicesServiceIdSlotsRouteImport.update({
  id: '/$serviceId/slots',
  path: '/$serviceId/slots',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesServiceIdDateRoute = ServicesServiceIdDateRouteImport.update({
  id: '/$serviceId/date',
  path: '/$serviceId/date',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$serviceId/date': typeof ServicesServiceIdDateRoute
  '/services/$serviceId/slots': typeof ServicesServiceIdSlotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRoute
  '/signup': typeof SignupRoute
  '/services': typeof ServicesIndexRoute
  '/services/$serviceId/date': typeof ServicesServiceIdDateRoute
  '/services/$serviceId/slots': typeof ServicesServiceIdSlotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$serviceId/date': typeof ServicesServiceIdDateRoute
  '/services/$serviceId/slots': typeof ServicesServiceIdSlotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/appointments'
    | '/login'
    | '/provider'
    | '/services'
    | '/signup'
    | '/services/'
    | '/services/$serviceId/date'
    | '/services/$serviceId/slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/appointments'
    | '/login'
    | '/provider'
    | '/signup'
    | '/services'
    | '/services/$serviceId/date'
    | '/services/$serviceId/slots'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/appointments'
    | '/login'
    | '/provider'
    | '/services'
    | '/signup'
    | '/services/'
    | '/services/$serviceId/date'
    | '/services/$serviceId/slots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AppointmentsRoute: typeof AppointmentsRoute
  LoginRoute: typeof LoginRoute
  ProviderRoute: typeof ProviderRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$serviceId/slots': {
      id: '/services/$serviceId/slots'
      path: '/$serviceId/slots'
      fullPath: '/services/$serviceId/slots'
      preLoaderRoute: typeof ServicesServiceIdSlotsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$serviceId/date': {
      id: '/services/$serviceId/date'
      path: '/$serviceId/date'
      fullPath: '/services/$serviceId/date'
      preLoaderRoute: typeof ServicesServiceIdDateRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesServiceIdDateRoute: typeof ServicesServiceIdDateRoute
  ServicesServiceIdSlotsRoute: typeof ServicesServiceIdSlotsRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesServiceIdDateRoute: ServicesServiceIdDateRoute,
  ServicesServiceIdSlotsRoute: ServicesServiceIdSlotsRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AppointmentsRoute: AppointmentsRoute,
  LoginRoute: LoginRoute,
  ProviderRoute: ProviderRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
